import { required } from "./config";

type Deployment = { url?: string; state?: string; readyState?: string; meta?: Record<string, string> };

/** Waits for the preview generated by Vercel's connected-Git integration after a sandbox push. */
export async function waitForPreview(branch: string) {
  const token = required("VERCEL_TOKEN");
  const projectId = required("VERCEL_PROJECT_ID");
  const team = process.env.VERCEL_TEAM_ID ? `&teamId=${encodeURIComponent(process.env.VERCEL_TEAM_ID)}` : "";
  for (let attempt = 0; attempt < 24; attempt++) {
    const response = await fetch(`https://api.vercel.com/v6/deployments?projectId=${encodeURIComponent(projectId)}&meta-githubCommitRef=${encodeURIComponent(branch)}${team}`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" });
    if (!response.ok) throw new Error(`Vercel preview lookup failed (${response.status}).`);
    const body = await response.json() as { deployments?: Deployment[] };
    const deployment = body.deployments?.[0];
    if (deployment?.readyState === "READY" && deployment.url) return `https://${deployment.url}`;
    if (deployment?.readyState === "ERROR" || deployment?.state === "ERROR") throw new Error("Vercel preview deployment failed.");
    await new Promise((resolve) => setTimeout(resolve, 5_000));
  }
  throw new Error("Timed out waiting for the Vercel preview deployment.");
}
